// examples/react/src/components/Input.tsx
import React from 'react';
import { Input as AInput, Form } from "antd"
import { FieldError } from './Error';
interface Props {
  errors: any;
  value: any
  onChange: any
  label: string
  isDisabled: boolean
  onBlur: Function
  onFocus: Function
  type?: "Group" | "Search" | "TextArea" | "Password" | "OTP" ;
}
export default function (props: Props) {
  const { onChange, value, errors, label, isDisabled, onBlur, onFocus , type } = props
  return <div>
    <Form.Item label={label}>
      <AInput disabled={isDisabled} value={value}
        onFocus={() => {
          onFocus()
        }}
        onBlur={(e) => {
          onBlur(e.target?.value  ?? e)
        }}
        onChange={(e) => {
          onChange(e?.target?.value ?? e)
        }} />
      <FieldError errors={errors} />
    </Form.Item>
  </div>
}

// examples/vue/src/components/Input.vue
<script setup lang="ts">
import { Input, Form } from "ant-design-vue"
interface Props {
  errors: any;
  value: any
  label: string
  isDisabled: boolean
  type?: "Group" | "Search" | "TextArea" | "Password" | "OTP";
}
defineOptions({
  inheritAttrs: false,
})
defineProps<Props>()
const emits = defineEmits(["change", "focus", "blur"])
const handleChange = (e: any) => {
  emits("change", e.target.value)
}
</script>

<template>
  <Form.Item :label="label">
    <Input :value="value" :disabled="isDisabled" @change="handleChange"/>
  </Form.Item>
</template>
